name: Update Deps
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0/6 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
    env:
      GH_READ_PACKAGES_TOKEN: ${{ secrets.GH_READ_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Check for new versions
        run: ./gradlew --no-daemon checkNewVersions
      - name: Apply version updates
        run: ./gradlew --no-daemon updateVersionsProps updatePlugins --write-locks
      - name: Create branch and commit changes
        run: |
          git config --local user.email "markelliot+gradle@gmail.com"
          git config --local user.name "Version Updates"
          git checkout -B auto/versions
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "Auto-update dependencies and plugins"
          git push github -f auto/versions
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_allow_empty: false
          pr_title: "Version Updates"

